### ISSUE TITLE
Reporting job error here: S291BWFLFRG9M3N

### ISSUE THREAD

**Issue by emilyyaklich** [cris12gm/normSeq#5]

**Comment by cris12gm** [comment]
Dear @emilyyaklich ,

Sorry for the inconvenience, we have checked the job ID and fixed it, please see the results here: 
https://arn.ugr.es/normSeq/results/?jobID=S291BWFLFRG9M3N

The problem was on the input annotation file, which was not tab-separated, please check that for future jobs.

Best,
Cristina

**Comment by emilyyaklich** [comment]
Hi Cristina,

Thank you for your reply - this makes sense! I do have another question,
for the Remove Unwanted Variation - RUVs method it is mentioned on the
input page that the annotation file must contain a third column with
replicate annotation - what is meant by this?

Emily

**Comment by cris12gm** [comment]
Dear Emily,

To perform the RUV method, the annotation file must contain a third column, like in the example below, where all samples that are replicates of one condition, have the same label. In the example below, there are 3 replicates of "cerebellum", and all of them are labeled as "Cerebellum" and 2 replicates of "cortex", and all of them are labeled as "Cortex". It must be also tab-separated.

sample	group	replicate
Cerebellum_1	CNS	Cerebellum
Cerebellum_2	CNS	Cerebellum
Cerebellum_3	CNS	Cerebellum
Cortex_1	CNS	Cortex
Cortex_2	CNS	Cortex

**Comment by XiaoweiKI** [comment]
There was error in NormSeq job ID 7ORUOUEENHB8BLU. Would you please check? Thanks!

**Comment by cris12gm** [comment]
Dear @XiaoweiKI ,

Sorry for the inconvenience, we have checked the job ID and fixed it, please see the results here:
We https://arn.ugr.es/normSeq/results/?jobID=7ORUOUEENHB8BLU

The problem was on the matrix file, which contained some duplicated rows. We optimized the website so from now on that shouldn't be a problem.

Best,
Cristina
