### ISSUE TITLE
Job ID: XDOMCGG848Y2VPS

### ISSUE THREAD

**Issue by alexanderkzee** [cris12gm/normSeq#6]
Error: Your annotation file has more than 10 groups, which is the maximum of NormSeq. Please relaunch with less groups.

Is there any way I can use normSeq with more than 10 groups?

**Comment by cris12gm** [comment]
Dear @alexanderkzee,

I'm sorry for the inconvenience, but currently, due to computational limitations, we can't allow more than 10 groups in normSeq. You can try to split your dataset into several analyses, where you have a max of 10 groups in each of them.
Also, I checked your job and it has no replicates, so if the purpose of the analysis was differential expression it would not be performed because it requires at least one group to have replicates.

Sorry for the inconvenience, best,

Cristina

**Comment by cris12gm** [comment]
Dear @alexanderkzee ,

We run your job internally, so avoid the 10 groups limitation, you can find the results here: https://arn.ugr.es/normSeq/results/?jobID=XDOMCGG848Y2VPS
But as I mentioned, the normal workflow of Normseq can only allow up to 10 groups, so in further analysis you will find the same problem.

Best,
Cristina

**Comment by alexanderkzee** [comment]
Thank you for this! I only wanted to do the normalization portion.

**Comment by cris12gm** [comment]
We will consider for future updates setting up an option to just get the normalized data, without the computational consuming analysis in these cases.
Thanks for the input and for using Normseq!

**Comment by alexanderkzee** [comment]
Hi i discovered an issue in my input matrix. Is there any way you could assist me again and rerun it for me? 
Job ID: 57JTNZZ2DKYT2PB

**Comment by cris12gm** [comment]
I just ran it, you can find the results here: https://arn.ugr.es/normSeq/status/?jobID=57JTNZZ2DKYT2PB

If you're only interested in the normalization, you can put all samples in the same group in the annotation file (as the algorithm only checks the number of different groups), and that would not affect the normalization of the matrix, and you can get it directly. This is what I now did in your dataset. 

In any case, in the following days, we will implement an update to allow just normalization of the data if there are more than 10 groups.
