### ISSUE TITLE
Error in Job id: MXJ1GEAF2S1D5EY

### ISSUE THREAD

**Issue by pablommesas** [cris12gm/normSeq#8]
Thanks!

**Comment by cris12gm** [comment]
Dear @pablommesas ,

Sorry for the big delay in our answer, we hope the problem was solved in another job. 
We checked the code and it was probably an issue with the server at the moment you launched your job. It's now working, please check the results in this page: https://arn.ugr.es/normSeq/results/?jobID=MXJ1GEAF2S1D5EY.

Best,
Cristina
